version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "VisitorCount"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tps8ds2dm7e1"
s3_prefix = "VisitorCount"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
