AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  My SAM App A much easier to follow tutorial than AWS' own.
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket

  FunctionCount:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        VisitorCount:
          Type: Api
          Properties:
            Path: /count
            Method: get
      Environment:
        Variables: 
          databaseName : !Ref MyTable  
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyTable        
  
  MyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: zacresumetable2
      PrimaryKey:
        Name: URL
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: false
      Tags:
        CostCenter: tutorials
        Chrislovessam: true
            
Outputs:
  VisitorCountApi:
    Description: "API Gateway endpoint URL for Prod stage for FunctionCount"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/count/"