name: test

on:
  push:

jobs:
  test:
    runs-on: windowslatest

    steps:
    - uses: actions/checkout@main

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install plugin
      run: pip install pytest-github-actions-annotate-failures

    - run: pytest
